### ISSUE TITLE
запуск

### ISSUE THREAD

**Issue by Jdunchik** [fedyacpp/BlumClicker#1]
при запуске python main.py выдает что то странное:
![Screenshot_28](https://github.com/fedyacpp/BlumClicker/assets/171877998/aee9d284-c87a-4590-b4b0-05cd917933a2)

**Comment by fedyacpp** [comment]
это не что то странное, если бы вы внимательно прочитали readme, то увидели бы это "Поместите скачанный файл весов (best.pt) в ту же директорию, что и скрипт, или укажите его путь при запуске скрипта.". То есть, если вы скачали best.pt и закинули его в папку со скриптом, то можете спокойно жать enter и всё, если же ~не~ нет, то вам требуется указать путь до него

**Comment by Jdunchik** [comment]
так дело в том, что я так и сделал, в итоге когда нажимаю enter ничего не происходит просто

**Comment by fedyacpp** [comment]
Можешь написать в дискорд/телеграм, юзернеймы везде одинаковые

**Comment by fedyacpp** [comment]
Для читающих из будущего: проблема была в недостатке информации в readme
