### ISSUE TITLE
Поддержка macOS 

### ISSUE THREAD

**Issue by mahlenko** [fedyacpp/BlumClicker#3]
Планируется ли поддержка macOS?

**Comment by fedyacpp** [comment]
Привет! Не планируется, т.к, начиная с macOS 10.14 Apple прекратила поддержку cuda [ссылка](https://developer.nvidia.com/nvidia-cuda-toolkit-11_6_0-developer-tools-mac-hosts#:~:text=however%2C%20is%20supported.-,Supported%20Mac%20platforms%3A%20macOS%2010.13,-To%20install%3A), да и в целом, сейчас в новых ноутбуках/компьютерах Apple, насколько я знаю, ставятся видеокарты от amd, либо их собственные. Разбираться как использовать те же чипы от яблока у меня нет времени, т.к я готовлюсь к ЕГЭ
