### ISSUE TITLE
Мемпад

### ISSUE THREAD

**Issue by Jdunchik** [fedyacpp/BlumClicker#4]
будет обнова с мемпадом?

**Comment by fedyacpp** [comment]
Что имеется ввиду под мемпадом?

**Comment by Jdunchik** [comment]
помимо снежинок будут падать dogs и в дальнейшем другие токены

**Comment by Jdunchik** [comment]
хотя ладно они его дали только 100к игрокам

**Comment by fedyacpp** [comment]
Как появится доступ - буду думать над реализацией
