### ISSUE TITLE
Blum added dogs token icon when playing game

### ISSUE THREAD

**Issue by be3rodnov** [fedyacpp/BlumClicker#5]
Blum just announced a new version game. Users can get dogs when playing game. Can you update scripts to catch dogs.

**Comment by fedyacpp** [comment]
where do you guys find those dogs? I don't have any so I'll update the script once I get them

**Comment by be3rodnov** [comment]
![image](https://github.com/user-attachments/assets/41d21188-a92c-4885-b179-3a23a2d55dc7)

**Comment by fedyacpp** [comment]
![Screenshot_20241016_220329](https://github.com/user-attachments/assets/34e10639-c0a1-4708-b5c5-80691f2536b7)
