### ISSUE TITLE
Click issue

### ISSUE THREAD

**Issue by Shisunlel** [fedyacpp/BlumClicker#6]
After the update, it doesn't click anymore. It only click like once every 5 seconds.
I'm not sure if it due to the new blum update with the U.S election because now there's Kamala and Trump coin too

![NVIDIA_Share_RjJwHzc90N](https://github.com/user-attachments/assets/8ddad2ad-7969-42e0-b6b2-40869a62ae45)

**Comment by fedyacpp** [comment]
that's 'cause i haven't reuploaded old weights, will do it in few minutes

**Comment by fedyacpp** [comment]
done, redownload weights
