### ISSUE TITLE
Issue with Game Autostart

### ISSUE THREAD

**Issue by tiditik** [fedyacpp/BlumClicker#7]
Hello!

I am experiencing a problem with the game's autostart feature. I am from Russia, and it seems that localization might be affecting this, as "Play" is displayed as "Играть" instead. I tried changing the language in Telegram, hoping it would help the system recognize that I am using the English localization, but it didn't work — "Играть" still appeared instead of "Play."

The only solution that worked was changing the code from "Play" to "Играть."

What should I do in this situation? Is there any solution to this problem?

**Comment by fedyacpp** [comment]
привет! да, решение есть: я ближе к вечеру по мск перепишу код, добавив туда обнаружение и того, и того

**Comment by fedyacpp** [comment]
~Привет ещё раз, я закомитил обновление, помимо обнаружения текста на двух языках, я ещё чуть-чуть оптимизировал сам скрипт, однако проверить его работоспособность у меня возможности нет. Если будут какие-то баги, можешь, пожалуйста, написать о них сюда?~ напортачил, сейчас быстренько исправлю

**Comment by fedyacpp** [comment]
готово, извиняюсь за задержки
